--CREAR USUARIO DE PROYECTO

CREATE USER DB_GOOD_SHOPPING
  IDENTIFIED BY "oracle"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;
ALTER USER DB_GOOD_SHOPPING QUOTA UNLIMITED ON USERS;

GRANT create session TO DB_GOOD_SHOPPING;
GRANT create table TO DB_GOOD_SHOPPING;
GRANT create view TO DB_GOOD_SHOPPING;
GRANT create any trigger TO DB_GOOD_SHOPPING;
GRANT create any procedure TO DB_GOOD_SHOPPING;
GRANT create sequence TO DB_GOOD_SHOPPING;
GRANT create synonym TO DB_GOOD_SHOPPING;
GRANT create materialized view TO DB_GOOD_SHOPPING;

-----Privilegio de creacion de job-------
GRANT CREATE JOB TO DB_GOOD_SHOPPING;
-----------------------------------------
